[2024-05-03T11:32:01.645+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T11:32:01.683+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-11T01:00:00+00:00 [queued]>
[2024-05-03T11:32:01.696+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-11T01:00:00+00:00 [queued]>
[2024-05-03T11:32:01.697+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-03T11:32:01.713+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): extract_data_from_api> on 2022-08-11 01:00:00+00:00
[2024-05-03T11:32:01.724+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=231) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-03T11:32:01.722+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_sales', 'extract_data_from_api', 'scheduled__2022-08-11T01:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmpp7wsx19a']
[2024-05-03T11:32:01.725+0000] {standard_task_runner.py:63} INFO - Started process 236 to run task
[2024-05-03T11:32:01.726+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask extract_data_from_api
[2024-05-03T11:32:01.741+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-03T11:32:01.785+0000] {task_command.py:426} INFO - Running <TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-11T01:00:00+00:00 [running]> on host 5137b2b1dc87
[2024-05-03T11:32:01.880+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2022-08-11T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-11T01:00:00+00:00'
[2024-05-03T11:32:01.881+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T11:32:01.896+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-03T11:32:01.897+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "http://host.docker.internal:8081/sales" -H "Content-Type: application/json" -d \'{"raw_dir":"file_storage/raw/sales/2022-08-11","date":"2022-08-11"}\')\n    if [ $response -ne 201 ]; then\n        echo "Request failed with status code $response"\n        exit 1\n    fi\n    ']
[2024-05-03T11:32:01.905+0000] {subprocess.py:86} INFO - Output:
[2024-05-03T11:32:01.919+0000] {subprocess.py:93} INFO - Request failed with status code 000
[2024-05-03T11:32:01.919+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-03T11:32:01.920+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T11:32:01.930+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-03T11:32:01.934+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=process_sales, task_id=extract_data_from_api, execution_date=20220811T010000, start_date=20240503T113201, end_date=20240503T113201
[2024-05-03T11:32:01.947+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task extract_data_from_api (Bash command failed. The command returned a non-zero exit code 1.; 236)
[2024-05-03T11:32:01.980+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-03T11:32:02.004+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-03T11:32:02.010+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-03T11:33:31.591+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T11:33:31.623+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-11T01:00:00+00:00 [queued]>
[2024-05-03T11:33:31.634+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-11T01:00:00+00:00 [queued]>
[2024-05-03T11:33:31.635+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-03T11:33:31.651+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): extract_data_from_api> on 2022-08-11 01:00:00+00:00
[2024-05-03T11:33:31.660+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=295) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-03T11:33:31.660+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_sales', 'extract_data_from_api', 'scheduled__2022-08-11T01:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmppbc71h0d']
[2024-05-03T11:33:31.663+0000] {standard_task_runner.py:63} INFO - Started process 301 to run task
[2024-05-03T11:33:31.663+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask extract_data_from_api
[2024-05-03T11:33:31.681+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-03T11:33:31.725+0000] {task_command.py:426} INFO - Running <TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-11T01:00:00+00:00 [running]> on host 5137b2b1dc87
[2024-05-03T11:33:31.835+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2022-08-11T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-11T01:00:00+00:00'
[2024-05-03T11:33:31.836+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T11:33:31.850+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-03T11:33:31.852+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "http://host.docker.internal:8081/sales" -H "Content-Type: application/json" -d \'{"raw_dir":"file_storage/raw/sales/2022-08-11","date":"2022-08-11"}\')\n    if [ $response -ne 201 ]; then\n        echo "Request failed with status code $response"\n        exit 1\n    fi\n    ']
[2024-05-03T11:33:31.862+0000] {subprocess.py:86} INFO - Output:
[2024-05-03T11:33:37.361+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-03T11:33:37.361+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T11:33:37.386+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=process_sales, task_id=extract_data_from_api, execution_date=20220811T010000, start_date=20240503T113331, end_date=20240503T113337
[2024-05-03T11:33:37.429+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-03T11:33:37.450+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-03T11:33:37.452+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
