[2024-05-03T11:31:01.160+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T11:31:01.216+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-12T01:00:00+00:00 [queued]>
[2024-05-03T11:31:01.230+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-12T01:00:00+00:00 [queued]>
[2024-05-03T11:31:01.244+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-03T11:31:01.264+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): extract_data_from_api> on 2022-08-12 01:00:00+00:00
[2024-05-03T11:31:01.271+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=199) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-03T11:31:01.272+0000] {standard_task_runner.py:63} INFO - Started process 211 to run task
[2024-05-03T11:31:01.271+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_sales', 'extract_data_from_api', 'scheduled__2022-08-12T01:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmp73n0n_bo']
[2024-05-03T11:31:01.273+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask extract_data_from_api
[2024-05-03T11:31:01.289+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-03T11:31:01.334+0000] {task_command.py:426} INFO - Running <TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-12T01:00:00+00:00 [running]> on host 5137b2b1dc87
[2024-05-03T11:31:01.432+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2022-08-12T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-12T01:00:00+00:00'
[2024-05-03T11:31:01.433+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T11:31:01.446+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-03T11:31:01.447+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "http://host.docker.internal:8081/sales" -H "Content-Type: application/json" -d \'{"raw_dir":"file_storage/raw/sales/2022-08-12","date":"2022-08-12"}\')\n    if [ $response -ne 201 ]; then\n        echo "Request failed with status code $response"\n        exit 1\n    fi\n    ']
[2024-05-03T11:31:01.456+0000] {subprocess.py:86} INFO - Output:
[2024-05-03T11:31:01.469+0000] {subprocess.py:93} INFO - Request failed with status code 000
[2024-05-03T11:31:01.470+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-03T11:31:01.471+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T11:31:01.482+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-03T11:31:01.486+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=process_sales, task_id=extract_data_from_api, execution_date=20220812T010000, start_date=20240503T113101, end_date=20240503T113101
[2024-05-03T11:31:01.502+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task extract_data_from_api (Bash command failed. The command returned a non-zero exit code 1.; 211)
[2024-05-03T11:31:01.527+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-03T11:31:01.551+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-03T11:31:01.553+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-03T11:32:31.034+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T11:32:31.071+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-12T01:00:00+00:00 [queued]>
[2024-05-03T11:32:31.081+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-12T01:00:00+00:00 [queued]>
[2024-05-03T11:32:31.082+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-03T11:32:31.097+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): extract_data_from_api> on 2022-08-12 01:00:00+00:00
[2024-05-03T11:32:31.106+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=264) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-03T11:32:31.106+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_sales', 'extract_data_from_api', 'scheduled__2022-08-12T01:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmpeawk69s8']
[2024-05-03T11:32:31.107+0000] {standard_task_runner.py:63} INFO - Started process 273 to run task
[2024-05-03T11:32:31.108+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask extract_data_from_api
[2024-05-03T11:32:31.121+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-03T11:32:31.158+0000] {task_command.py:426} INFO - Running <TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-12T01:00:00+00:00 [running]> on host 5137b2b1dc87
[2024-05-03T11:32:31.250+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2022-08-12T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-12T01:00:00+00:00'
[2024-05-03T11:32:31.251+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T11:32:31.263+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-03T11:32:31.265+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "http://host.docker.internal:8081/sales" -H "Content-Type: application/json" -d \'{"raw_dir":"file_storage/raw/sales/2022-08-12","date":"2022-08-12"}\')\n    if [ $response -ne 201 ]; then\n        echo "Request failed with status code $response"\n        exit 1\n    fi\n    ']
[2024-05-03T11:32:31.273+0000] {subprocess.py:86} INFO - Output:
[2024-05-03T11:32:31.285+0000] {subprocess.py:93} INFO - Request failed with status code 000
[2024-05-03T11:32:31.286+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-03T11:32:31.287+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T11:32:31.298+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-03T11:32:31.302+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=process_sales, task_id=extract_data_from_api, execution_date=20220812T010000, start_date=20240503T113231, end_date=20240503T113231
[2024-05-03T11:32:31.313+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task extract_data_from_api (Bash command failed. The command returned a non-zero exit code 1.; 273)
[2024-05-03T11:32:31.322+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-03T11:32:31.345+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-03T11:32:31.347+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
