[2024-05-03T11:32:01.758+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T11:32:01.798+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-12T01:00:00+00:00 [queued]>
[2024-05-03T11:32:01.808+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-12T01:00:00+00:00 [queued]>
[2024-05-03T11:32:01.810+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-03T11:32:01.826+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): extract_data_from_api> on 2022-08-12 01:00:00+00:00
[2024-05-03T11:32:01.832+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=234) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-03T11:32:01.832+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_sales', 'extract_data_from_api', 'scheduled__2022-08-12T01:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmp7nr6dr__']
[2024-05-03T11:32:01.833+0000] {standard_task_runner.py:63} INFO - Started process 243 to run task
[2024-05-03T11:32:01.833+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask extract_data_from_api
[2024-05-03T11:32:01.848+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-03T11:32:01.889+0000] {task_command.py:426} INFO - Running <TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-12T01:00:00+00:00 [running]> on host 5137b2b1dc87
[2024-05-03T11:32:01.977+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2022-08-12T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-12T01:00:00+00:00'
[2024-05-03T11:32:01.978+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T11:32:01.990+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-03T11:32:01.991+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "http://host.docker.internal:8081/sales" -H "Content-Type: application/json" -d \'{"raw_dir":"file_storage/raw/sales/2022-08-12","date":"2022-08-12"}\')\n    if [ $response -ne 201 ]; then\n        echo "Request failed with status code $response"\n        exit 1\n    fi\n    ']
[2024-05-03T11:32:01.999+0000] {subprocess.py:86} INFO - Output:
[2024-05-03T11:32:02.012+0000] {subprocess.py:93} INFO - Request failed with status code 000
[2024-05-03T11:32:02.012+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-03T11:32:02.013+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T11:32:02.024+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-03T11:32:02.029+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=process_sales, task_id=extract_data_from_api, execution_date=20220812T010000, start_date=20240503T113201, end_date=20240503T113202
[2024-05-03T11:32:02.041+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task extract_data_from_api (Bash command failed. The command returned a non-zero exit code 1.; 243)
[2024-05-03T11:32:02.088+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-03T11:32:02.113+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-03T11:32:02.118+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-03T11:33:31.586+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T11:33:31.617+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-12T01:00:00+00:00 [queued]>
[2024-05-03T11:33:31.627+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-12T01:00:00+00:00 [queued]>
[2024-05-03T11:33:31.628+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-03T11:33:31.645+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): extract_data_from_api> on 2022-08-12 01:00:00+00:00
[2024-05-03T11:33:31.653+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=294) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-03T11:33:31.655+0000] {standard_task_runner.py:63} INFO - Started process 299 to run task
[2024-05-03T11:33:31.654+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_sales', 'extract_data_from_api', 'scheduled__2022-08-12T01:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmprxvcot5i']
[2024-05-03T11:33:31.657+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask extract_data_from_api
[2024-05-03T11:33:31.675+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-03T11:33:31.719+0000] {task_command.py:426} INFO - Running <TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-12T01:00:00+00:00 [running]> on host 5137b2b1dc87
[2024-05-03T11:33:31.822+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2022-08-12T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-12T01:00:00+00:00'
[2024-05-03T11:33:31.824+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T11:33:31.844+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-03T11:33:31.845+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "http://host.docker.internal:8081/sales" -H "Content-Type: application/json" -d \'{"raw_dir":"file_storage/raw/sales/2022-08-12","date":"2022-08-12"}\')\n    if [ $response -ne 201 ]; then\n        echo "Request failed with status code $response"\n        exit 1\n    fi\n    ']
[2024-05-03T11:33:31.856+0000] {subprocess.py:86} INFO - Output:
[2024-05-03T11:33:34.890+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-03T11:33:34.891+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T11:33:34.918+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=process_sales, task_id=extract_data_from_api, execution_date=20220812T010000, start_date=20240503T113331, end_date=20240503T113334
[2024-05-03T11:33:34.970+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-03T11:33:34.991+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-03T11:33:34.993+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
