[2024-05-03T11:32:01.455+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T11:32:01.493+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-09T01:00:00+00:00 [queued]>
[2024-05-03T11:32:01.507+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-09T01:00:00+00:00 [queued]>
[2024-05-03T11:32:01.509+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-03T11:32:01.541+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): extract_data_from_api> on 2022-08-09 01:00:00+00:00
[2024-05-03T11:32:01.549+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=229) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-03T11:32:01.549+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_sales', 'extract_data_from_api', 'scheduled__2022-08-09T01:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmpeh8p9a88']
[2024-05-03T11:32:01.551+0000] {standard_task_runner.py:63} INFO - Started process 233 to run task
[2024-05-03T11:32:01.552+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask extract_data_from_api
[2024-05-03T11:32:01.572+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-03T11:32:01.619+0000] {task_command.py:426} INFO - Running <TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-09T01:00:00+00:00 [running]> on host 5137b2b1dc87
[2024-05-03T11:32:01.722+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2022-08-09T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-09T01:00:00+00:00'
[2024-05-03T11:32:01.723+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T11:32:01.740+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-03T11:32:01.742+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "http://host.docker.internal:8081/sales" -H "Content-Type: application/json" -d \'{"raw_dir":"file_storage/raw/sales/2022-08-09","date":"2022-08-09"}\')\n    if [ $response -ne 201 ]; then\n        echo "Request failed with status code $response"\n        exit 1\n    fi\n    ']
[2024-05-03T11:32:01.752+0000] {subprocess.py:86} INFO - Output:
[2024-05-03T11:32:01.766+0000] {subprocess.py:93} INFO - Request failed with status code 000
[2024-05-03T11:32:01.767+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-03T11:32:01.768+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T11:32:01.780+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-03T11:32:01.786+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=process_sales, task_id=extract_data_from_api, execution_date=20220809T010000, start_date=20240503T113201, end_date=20240503T113201
[2024-05-03T11:32:01.799+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task extract_data_from_api (Bash command failed. The command returned a non-zero exit code 1.; 233)
[2024-05-03T11:32:01.806+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-03T11:32:01.831+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-03T11:32:01.836+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-03T11:33:31.591+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T11:33:31.623+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-09T01:00:00+00:00 [queued]>
[2024-05-03T11:33:31.635+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-09T01:00:00+00:00 [queued]>
[2024-05-03T11:33:31.636+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-03T11:33:31.653+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): extract_data_from_api> on 2022-08-09 01:00:00+00:00
[2024-05-03T11:33:31.663+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_sales', 'extract_data_from_api', 'scheduled__2022-08-09T01:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmprz7irkx9']
[2024-05-03T11:33:31.663+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=296) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-03T11:33:31.665+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask extract_data_from_api
[2024-05-03T11:33:31.665+0000] {standard_task_runner.py:63} INFO - Started process 302 to run task
[2024-05-03T11:33:31.682+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-03T11:33:31.725+0000] {task_command.py:426} INFO - Running <TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-09T01:00:00+00:00 [running]> on host 5137b2b1dc87
[2024-05-03T11:33:31.830+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2022-08-09T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-09T01:00:00+00:00'
[2024-05-03T11:33:31.831+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T11:33:31.846+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-03T11:33:31.848+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "http://host.docker.internal:8081/sales" -H "Content-Type: application/json" -d \'{"raw_dir":"file_storage/raw/sales/2022-08-09","date":"2022-08-09"}\')\n    if [ $response -ne 201 ]; then\n        echo "Request failed with status code $response"\n        exit 1\n    fi\n    ']
[2024-05-03T11:33:31.857+0000] {subprocess.py:86} INFO - Output:
[2024-05-03T11:33:37.252+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-03T11:33:37.253+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T11:33:37.278+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=process_sales, task_id=extract_data_from_api, execution_date=20220809T010000, start_date=20240503T113331, end_date=20240503T113337
[2024-05-03T11:33:37.304+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-03T11:33:37.325+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-03T11:33:37.327+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
